---
repo-name: peripherals-aws-ecs
categories:
  - Cloud
  - DevOps
display-name: Amazon ECS
manufacturer: Amazon
product: ECS
description: Amazon Elastic Container Service (Amazon ECS) is a highly scalable, high-performance container orchestration service that supports Docker containers and allows you to easily run and scale containerized applications on AWS.
